[package]
name = "utils"
version = "0.1.0"
description = ""
edition = { workspace = true }

[dependencies]
anyhow = "1"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.159", features = ["derive"] }